name: dartkt
description: A dart library for lazier programmers. Functions are ported from kotlin.
version: 1.0.5
homepage: https://github.com/codemonarch/dartkt

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  convert: ^3.0.0
  crypto: ^3.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
